version: '3'

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    volumes:
      - ./backend:/var/www/oktrening
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - backend
      - db

  backend:
    build: docker/backend
    container_name: backend
    working_dir: /var/www/oktrening
    volumes:
      - ./backend:/var/www/oktrening
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_PASSWORD: qwerty123_
      MYSQL_ROOT_PASSWORD: qwerty123_
      MYSQL_DATABASE: oktrening
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql